#ifndef QTMATERIAL_GLOBAL_H
#define QTMATERIAL_GLOBAL_H

#ifndef QMATERIAL_STATIC_EXPORT
#ifdef  QMATERIAL_SHARED_EXPORT
// #define MATERIAL_EXPORT
#define MATERIAL_EXPORT Q_DECL_EXPORT
#else
// #define MATERIAL_EXPORT
#define MATERIAL_EXPORT Q_DECL_IMPORT
#endif
#else
#define MATERIAL_EXPORT
#endif

#endif